### ISSUE TITLE
Need to update encoding guidelines for this project

### ISSUE THREAD

**Issue by MaryIsbell** [MaryIsbell/TheYoungIdea#3]
I will probably keep these guidelines as a google spreadsheet instead of uploading them here?? Google spreadsheets maintain a record of edits over time. Although it might be better if I upload a spreadsheet here because there will be a very visible record within this repository every time an encoding guideline is tweaked. We will tweak guidelines often as we encounter new phenomena in the text and when that happens we'll need to update all files to remain consistent. I'm leaning toward converting the current google spreadsheet to an excel spreadsheet and uploading it here. Thoughts @noorka?

**Comment by noorka** [comment]
I think with the google doc there is the pro of having it readily available and easy to edit, however having it on here means that more of the resources are in one location rather than many different locations. Maybe keeping both? Then again it would be a hassle to update both. I guess it really comes down to how centralized you want the information to be.

**Comment by MaryIsbell** [comment]
I didn't write down the great idea I had about this--I think it was just to include the link to the encoding guidelines and then perhaps make a note each time these were updated? We're working on TIAN now, so we'll resolve it there and follow the same plan over here.
